### ISSUE TITLE
Fix TypeError in handle_file_and_optional_link()

### ISSUE THREAD

**Issue by novoid** [novoid/filetags#22]
Error occurred when invoking on Windows 10 test file structure.

Maybe it is caused by a duplicate file (`file -- foo bar.txt`) in two different folders which should be caught and handled appropriately.

See verbose output for details:

```
DEBUG    2018-06-01 14:10:48,862 create_link(C:\Users\karl.voit\2del\bar -- cust-nam draft internaluse foo bar.txt, C:\Users\karl.voit\.filetags_tagfilter\bar -- cust-nam draft internaluse foo bar.txt) called
DEBUG    2018-06-01 14:10:48,870 handle_file_and_optional_link("C:\Users\karl.voit\2del\bar -- cust-nam draft internaluse foo bar.txt") FINISHED  ????????????????????
DEBUG    2018-06-01 14:10:48,870 list_of_link_directories: []
DEBUG    2018-06-01 14:10:48,871 is_broken_link(C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt)  is not a lnk file at all; thus: not a broken link
DEBUG    2018-06-01 14:10:48,871 handle_file_and_optional_link("C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt")   ????????????????????
DEBUG    2018-06-01 14:10:48,872 handle_file_and_optional_link: changing to dir "C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files"
DEBUG    2018-06-01 14:10:48,872 handle_file_and_optional_link: file is not a non-broken link (False) or TAG_LINK_ORIGINALS_WHEN_TAGGING_LINKS is not set
DEBUG    2018-06-01 14:10:48,872 handle_file_and_optional_link: after handling potential link originals, I now handle the file we were talking about in the first place: C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt
DEBUG    2018-06-01 14:10:48,873 handle_file("C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt") ##########   with working dir "C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files"
 linking  "file -- foo bar.txt"
             ?   ".filetags_tagfilter"
DEBUG    2018-06-01 14:10:48,874 create_link(C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt, C:\Users\karl.voit\.filetags_tagfilter\file -- foo bar.txt) called
DEBUG    2018-06-01 14:10:48,882 handle_file_and_optional_link("C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt") FINISHED  ????????????????????
DEBUG    2018-06-01 14:10:48,882 list_of_link_directories: []
DEBUG    2018-06-01 14:10:48,893 is_broken_link(C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt.lnk) == C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt  which does exist -> non-broken link
DEBUG    2018-06-01 14:10:48,894 handle_file_and_optional_link("C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt.lnk")   ????????????????????
DEBUG    2018-06-01 14:10:48,901 handle_file_and_optional_link: file is a non-broken link (and TAG_LINK_ORIGINALS_WHEN_TAGGING_LINKS is set)
DEBUG    2018-06-01 14:10:48,907 get_link_source_file(C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt.lnk) == C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt  which does exist -> non-broken link
DEBUG    2018-06-01 14:10:48,908 handle_file_and_optional_link: link "C:\Users\karl.voit\2del\2018-05-11_backup-tmp\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt.lnk" has same basename as its source file "C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt"  vvvvvvvvvvvvvvvvvvvv
DEBUG    2018-06-01 14:10:48,908 handle_file_and_optional_link: invoking handle_file_and_optional_link("C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt")  vvvvvvvvvvvvvvvvvvvv
DEBUG    2018-06-01 14:10:48,908 handle_file_and_optional_link("C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt")   ????????????????????
DEBUG    2018-06-01 14:10:48,909 handle_file_and_optional_link: changing to dir "C:\Users\karl.voit\src\filetags\manualtests\test lnk files"
DEBUG    2018-06-01 14:10:48,910 handle_file_and_optional_link: file is not a non-broken link (False) or TAG_LINK_ORIGINALS_WHEN_TAGGING_LINKS is not set
DEBUG    2018-06-01 14:10:48,910 handle_file_and_optional_link: after handling potential link originals, I now handle the file we were talking about in the first place: C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt
DEBUG    2018-06-01 14:10:48,910 handle_file("C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt") ##########   with working dir "C:\Users\karl.voit\src\filetags\manualtests\test lnk files"
 linking  "file -- foo bar.txt"
             ?   ".filetags_tagfilter"
DEBUG    2018-06-01 14:10:48,911 create_link(C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt, C:\Users\karl.voit\.filetags_tagfilter\file -- foo bar.txt) called
DEBUG    2018-06-01 14:10:48,924 handle_file_and_optional_link("C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt") FINISHED  ????????????????????
DEBUG    2018-06-01 14:10:48,924 handle_file_and_optional_link: RETURNED handle_file_and_optional_link("C:\Users\karl.voit\src\filetags\manualtests\test lnk files\file -- foo bar.txt")  vvvvvvvvvvvvvvvvvvvv
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\filetags.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\filetags\__init__.py", line 2626, in main
    options.dryrun)
  File "c:\python36\lib\site-packages\filetags\__init__.py", line 910, in handle_file_and_optional_link
    new_source_filename = os.path.join(old_source_dirname, new_source_basename)
  File "c:\python36\lib\ntpath.py", line 114, in join
    genericpath._check_arg_types('join', path, *paths)
  File "c:\python36\lib\genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by novoid** [comment]
Can't reproduce the issue on Linux. Must analyze it on Windows.

**Comment by novoid** [comment]
Can not re-produce the issue on Windows any more :-(
