### ISSUE TITLE
I'm not able to run filetags on Virtual Centos Install

### ISSUE THREAD

**Issue by AlpsDevABE** [novoid/filetags#35]
When attempting to run filetags I get the following: 

```
$ filetags -v
Traceback (most recent call last):
  File "/home/alpsdev/.local/bin/filetags", line 5, in <module>
    from filetags import main
  File "/home/alpsdev/.local/lib/python3.9/site-packages/filetags/__init__.py", line 51, in <module>
    save_import('readline')   # for raw_input() reading from stdin
  File "/home/alpsdev/.local/lib/python3.9/site-packages/filetags/__init__.py", line 35, in save_import
    globals()[library] = import_module(library)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/alpsdev/.local/lib/python3.9/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/home/alpsdev/.local/lib/python3.9/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/home/alpsdev/.local/lib/python3.9/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/home/alpsdev/.local/lib/python3.9/site-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
    from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
  File "/home/alpsdev/.local/lib/python3.9/site-packages/pyreadline/keysyms/__init__.py", line 23, in <module>
    raise ImportError("Could not import keysym for local pythonversion", x)
NameError: name 'x' is not defined
```
I installed it via pip
Python is an altinstall of 3.9 since centos uses it's own version that is 2.x

````
$ pip3 install date2name appendfilename filetags integratethis
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: date2name in /home/***/.local/lib/python3.9/site-packages (2018.5.9.1)
Requirement already satisfied: appendfilename in /home/***/.local/lib/python3.9/site-packages (2020.6.7.1)
Requirement already satisfied: filetags in /home/***/.local/lib/python3.9/site-packages (2021.4.3.1)
Requirement already satisfied: integratethis in /home/***/.local/lib/python3.9/site-packages (2020.1.8.1)
Requirement already satisfied: pyreadline in /home/***/.local/lib/python3.9/site-packages (from appendfilename) (2.1)
Requirement already satisfied: colorama in /home/***/.local/lib/python3.9/site-packages (from filetags) (0.4.4)
Requirement already satisfied: clint in /home/***/.local/lib/python3.9/site-packages (from filetags) (0.5.1)
Requirement already satisfied: args in /home/***/.local/lib/python3.9/site-packages (from clint->filetags) (0.1.0)
````

I am using Gnome-Terminal WindowMaker not sure if that would cause an issue => Trying with xterm => Same Result
Trying in pure terminal => Same result

Let me know if you need anything else. 

Thank you for such an awesome set of tools!!!

**Comment by novoid** [comment]
Hi @AlpsDevABE ,

The first error message you provide seems to be related to an issue with the `readline` library which is not written or provided by me. So if there is a bug, you would have to clarify with the `readline` library instead since I can't reproduce the error case here.

To me, it looks like https://github.com/pyreadline/pyreadline/blob/master/pyreadline/keysyms/__init__.py is not able to load a library named `keysyms`. Unfortunately, this is not something where I can help.

As of terminals: filetags should be independent of a terminal application to my understanding. You're dealing with a Python bug of a library which is used by `filetags`.  So any other Python tool that is using the `readline` or `keysyms` would fail as well.

Furthermore, you don't need `integratethis` on non-Windows systems since it currently only helps with integration to Windows File Explorer.

I'm glad that my tools provide you some benefit in your digital work!
