### ISSUE TITLE
.filetags Error on windows

### ISSUE THREAD

**Issue by Bassmann** [novoid/filetags#6]
I try to use the .filetags facility but get the following error:
```
Traceback (most recent call last):
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python36\Scripts\filetags.exe\__main__.py", line 9, in <module>
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\site-packages\filetags\__init__.py", line 1819, in main
    vocabulary = sorted(locate_and_parse_controlled_vocabulary(False))
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\site-packages\filetags\__init__.py", line 1158, in locate_and_parse_controlled_vocabulary
    for rawline in filehandle:
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\codecs.py", line 713, in __next__
    return next(self.reader)
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\codecs.py", line 644, in __next__
    line = self.readline()
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\codecs.py", line 557, in readline
    data = self.read(readsize, firstline=True)
  File "c:\users\<USER>\appdata\local\programs\python\python36\lib\codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
```
It's the same both if I choose Unicode and if I choose ANSI to save the file. Any idea what I'm doing wrong?

**Comment by novoid** [comment]
Could you please send me the .filetags file? If you don't want to include it here publicly, you can use the email address from the help page of filetags.

Also: could you please run this using the verbose command line parameter so that I can get the full version?

Thanks!

**Comment by Bassmann** [comment]
Probably user error. I tried today again and firstly realized that some of hte tags used umlauts. Removing those made the error go away but then adding them again and saving as utf-8 worked as well.

Sorry for bothering you and thanks for the fast response: open source at its best!

**Comment by novoid** [comment]
No worries.

I am not using any non-7-bit-ASCII characters myself in .filetags. However, using Python 3 and UTF-8 we should be safe in any case.

Happy tagging!
