### ISSUE TITLE
Tagging files outside of their directory fails

### ISSUE THREAD

**Issue by MyFedora** [novoid/filetags#60]
### Steps to reproduce

```
$ mkdir example/
$ touch example/file.txt
$ filetags --verbose example/file.txt
DEBUG    2023-08-19 19:52:24,250 extracting list of files ...
DEBUG    2023-08-19 19:52:24,251 len(options.files) [1]
DEBUG    2023-08-19 19:52:24,251 1 filenames found: [example/file.txt]
DEBUG    2023-08-19 19:52:24,251 reported console width: 190 and height: 45   (80/80 is the fall-back)
DEBUG    2023-08-19 19:52:24,251 locate_and_parse_controlled_vocabulary: called with startfile: "example/file.txt"
DEBUG    2023-08-19 19:52:24,251 locate_and_parse_controlled_vocabulary: called in cwd: /home/user/Documents
DEBUG    2023-08-19 19:52:24,251 locate_file_in_cwd_and_parent_directories: called with startfile "example/file.txt" and filename ".filetags" ..
DEBUG    2023-08-19 19:52:24,251 locate_file_in_cwd_and_parent_directories: startfile [example/file.txt] found, using it as starting_dir [/home/user/Documents/example] ....
DEBUG    2023-08-19 19:52:24,251 locate_file_in_cwd_and_parent_directories: looking for ".filetags" in directory "/home/user/Documents" .......
DEBUG    2023-08-19 19:52:24,251 locate_file_in_cwd_and_parent_directories: did NOT find ".filetags" in current directory or any parent directory
DEBUG    2023-08-19 19:52:24,251 locate_and_parse_controlled_vocabulary: locate_file_in_cwd_and_parent_directories did NOT find any filename
DEBUG    2023-08-19 19:52:24,251 locate_and_parse_controlled_vocabulary: could not derive filename for controlled vocabulary
DEBUG    2023-08-19 19:52:24,251 split_up_filename(example/file.txt) does NOT exist. Playing along and returning non-existent filename parts.
DEBUG    2023-08-19 19:52:24,251 found common tags: tags_intersection_of_files[]
DEBUG    2023-08-19 19:52:24,251 split_up_filename(example/file.txt) does NOT exist. Playing along and returning non-existent filename parts.
DEBUG    2023-08-19 19:52:24,251 deriving upto9_tags_for_shortcuts ...
```
```py
Traceback (most recent call last):
  File "/home/user/.local/bin/filetags", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/pipx/venvs/filetags/lib/python3.11/site-packages/filetags/__init__.py", line 2664, in main
    get_tags_from_files_and_subfolders(
  File "/home/user/.local/pipx/venvs/filetags/lib/python3.11/site-packages/filetags/__init__.py", line 1241, in get_tags_from_files_and_subfolders
    assert(os.path.isdir(startdir))
AssertionError
```

```
$ cd example/
$ filetags --verbose file.txt
DEBUG    2023-08-19 19:59:24,103 extracting list of files ...
DEBUG    2023-08-19 19:59:24,103 len(options.files) [1]
DEBUG    2023-08-19 19:59:24,103 1 filenames found: [file.txt]
DEBUG    2023-08-19 19:59:24,103 reported console width: 190 and height: 45   (80/80 is the fall-back)
DEBUG    2023-08-19 19:59:24,103 locate_and_parse_controlled_vocabulary: called with startfile: "file.txt"
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: called in cwd: /home/user/Documents/example
DEBUG    2023-08-19 19:59:24,104 locate_file_in_cwd_and_parent_directories: called with startfile "file.txt" and filename ".filetags" ..
DEBUG    2023-08-19 19:59:24,104 locate_file_in_cwd_and_parent_directories: startfile [file.txt] found, using it as starting_dir [/home/user/Documents/example] ....
DEBUG    2023-08-19 19:59:24,104 locate_file_in_cwd_and_parent_directories: looking for ".filetags" in directory "/home/user/Documents" .......
DEBUG    2023-08-19 19:59:24,104 locate_file_in_cwd_and_parent_directories: found ".filetags" in directory "/home/user" ........
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: locate_file_in_cwd_and_parent_directories returned: /home/user/.filetags
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: .filetags found: /home/user/.filetags
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: found controlled vocabulary
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: reading controlled vocabulary in [/home/user/.filetags]
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: found unique tags: draft final
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: controlled vocabulary has 17 tags
DEBUG    2023-08-19 19:59:24,104 locate_and_parse_controlled_vocabulary: controlled vocabulary has 1 groups of unique tags
DEBUG    2023-08-19 19:59:24,104 found common tags: tags_intersection_of_files[]
DEBUG    2023-08-19 19:59:24,104 deriving upto9_tags_for_shortcuts ...
DEBUG    2023-08-19 19:59:24,104 get_tags_from_files_and_subfolders called with startdir [/home/user/Documents/example], cached startdirs [0]
DEBUG    2023-08-19 19:59:24,104 get_tags_from_files_and_subfolders: Writing 0 tags in cache for directory: /home/user/Documents/example
DEBUG    2023-08-19 19:59:24,104 get_upto_nine_keys_of_dict_with_highest_value: complete_list: 
DEBUG    2023-08-19 19:59:24,105 derived upto9_tags_for_shortcuts
DEBUG    2023-08-19 19:59:24,105 derived vocabulary with 17 entries
DEBUG    2023-08-19 19:59:24,105 len(files) [1]
DEBUG    2023-08-19 19:59:24,105 files: ['file.txt']
                 
Please enter tags, separated by " "; abort with Ctrl-C; complete 17 tags with TAB
                     
         .--------, 
        | o   ?   | 
         `--------' 
                     
DEBUG    2023-08-19 19:59:24,105 interactive mode: asking for tags ...
Tags: 
```

### Root cause

A bunch of functions call `os.chdir` while others assume that the working directory is the original working directory. We also assume that `os.path.abs` generates a valid absolute path, but `os.path.abs` relies on the working directory to generate an absolute path. If filetags switches to `/path/to/tagtrees`, but the file argument is `tagtrees/file.txt`, `os.path.abs` generates `/path/to/tagtrees/tagtrees/file.txt`, which is obviously not what we want.

**Comment by novoid** [comment]
Yes, this is nasty. Let's hope that the future patch will catch all the edge-cases.

**Comment by novoid** [comment]
OMG, `os.path.abspath(files[0])` doesn't return the absolute path of `file[0]` independent from the current working directory. :astonished: 

I hope this fix doesn't produce any side-effects. The code base is complex enough that I can't guarantee any negative side-effects. The unit test I added didn't show the error and unit tests aren't covering all the functionality. Please do report back any issue.
