### ISSUE TITLE
symlinks already exist in .filetags_tagfilter and crash

### ISSUE THREAD

**Issue by DeutscheGabanna** [novoid/filetags#65]
Why does the `filetags -f` fail if there are already symlinks with that name created at `.filetags_tagfilter`? In my opinion it should just skip them, not throw an error.

```
(base) [deutschegabanna@arch vault]$ filetags -f *
                 
Please enter tags, separated by " "; abort with Ctrl-C; complete 4 tags with TAB
                     
         .--------, 
        | o   ?   | 
         `--------' 
                     

  Used tags in this directory:
    one (1) ⋅ two (2) ⋅ three (3) ⋅ four (4)

Tags: 2

INFO     filtering items with tag(s) "health" and linking to directory "/home/deutschegabanna/.filetags_tagfilter" ...
  something.md                      ――linking―→   .filetags_tagfilter
Traceback (most recent call last):
  File "/usr/local/bin/filetags", line 2752, in <module>
    main()
  File "/usr/local/bin/filetags", line 2725, in main
    handle_file_and_optional_link(filename,
  File "/usr/local/bin/filetags", line 976, in handle_file_and_optional_link
    new_filename = handle_file(filename, tags, do_remove, do_filter, dryrun)
  File "/usr/local/bin/filetags", line 1060, in handle_file
    create_link(filename, os.path.join(chosen_tagtrees_dir, basename))
  File "/usr/local/bin/filetags", line 1029, in create_link
    os.symlink(source, destination)
FileExistsError: [Errno 17] File exists: '/home/deutschegabanna/vault/something.md' -> '/home/deutschegabanna/.filetags_tagfilter/something.md'
```

**Comment by DeutscheGabanna** [comment]
```
DEBUG    2023-10-30 16:32:14,457 interactive mode: asking for tags ...
Tags: 1
DEBUG    2023-10-30 16:32:55,916 tag is an integer; stepping through the integers
DEBUG    2023-10-30 16:32:55,916 adding shortcut tags of number(s) 1

DEBUG    2023-10-30 16:32:55,916 tags found: [test]
INFO     2023-10-30 16:32:55,916 filtering items with tag(s) "test" and linking to directory "/home/deutschegabanna/.filetags_tagfilter" ...
DEBUG    2023-10-30 16:32:55,916 iterate over files ...
DEBUG    2023-10-30 16:32:55,916 determined maximum file name length with 62
DEBUG    2023-10-30 16:32:55,916 handle_file_and_optional_link("2022-Q3 Rachunek.md") …  ★★★★★★★★★★★★★★★★★★★★
DEBUG    2023-10-30 16:32:55,916 handle_file_and_optional_link: file is not a non-broken link (None) or TAG_LINK_ORIGINALS_WHEN_TAGGING_LINKS is not set
DEBUG    2023-10-30 16:32:55,916 handle_file_and_optional_link: after handling potential link originals, I now handle the file we were talking about in the first place: /home/deutschegabanna/vault/2022-Q3 Rachunek.md
DEBUG    2023-10-30 16:32:55,916 handle_file("/home/deutschegabanna/vault/2022-Q3 Rachunek.md") ##########  … with working dir "/home/deutschegabanna/vault"
  2022-Q3 Rachunek.md                      ――linking―→   .filetags_tagfilter
DEBUG    2023-10-30 16:32:55,916 create_link(/home/deutschegabanna/vault/2022-Q3 Rachunek.md, /home/deutschegabanna/.filetags_tagfilter/2022-Q3 Rachunek.md) called
Traceback (most recent call last):
  File "/usr/local/bin/filetags", line 2752, in <module>
    main()
  File "/usr/local/bin/filetags", line 2725, in main
    handle_file_and_optional_link(filename,
  File "/usr/local/bin/filetags", line 976, in handle_file_and_optional_link
    new_filename = handle_file(filename, tags, do_remove, do_filter, dryrun)
  File "/usr/local/bin/filetags", line 1060, in handle_file
    create_link(filename, os.path.join(chosen_tagtrees_dir, basename))
  File "/usr/local/bin/filetags", line 1029, in create_link
    os.symlink(source, destination)
FileNotFoundError: [Errno 2] No such file or directory: '/home/deutschegabanna/vault/2022-Q3 Rachunek.md' -> '/home/deutschegabanna/.filetags_tagfilter/2022-Q3 Rachunek.md'
(base) [deutschegabanna@arch vault]$ cat ~/vault/2022-Q3\ Rachunek.md 
---
isDigital: false
placement: blue document protector 
---
sth
152 kWh - 134.99 PLN(base) [deutschegabanna@arch vault]$
```

**Comment by novoid** [comment]
Good point. I've added a new option "--overwrite" you can use now.

Background: So far, I've been using a wrapper script which handles the cleanup before re-creating tagtrees and filters and more.
