### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable'`

### ISSUE THREAD

**Issue by peekaa** [novoid/filetags#67]
Clean install python 3.12 and pip install filetags, makes this after running python:
`C:\>python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "<frozen site>", line 450, in register_readline
  File "C:\prg\Python312\Lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
         ^^^^^^^^^^
  File "C:\prg\Python312\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\prg\Python312\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\prg\Python312\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\prg\Python312\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\prg\Python312\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'`

win 10

Thank you for help.

**Comment by novoid** [comment]
https://github.com/novoid/filetags/issues?q=is%3Aissue+is%3Aclosed+Callable
Pick one :wink:

**Comment by peekaa** [comment]
pip uninstall pyreadline
pip install pyreadline3

**Comment by novoid** [comment]
Thanks @peekaa, because of the multiple issues in recent time, I re-checked and actually found an outdated dependency in setup.py which caused the wrong pypi dependency. This is fixed now.

Sorry for the fuzz and thanks for reporting!
